deploy_dev:
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  stage: deploy
  script:
    - docker rm -f hrerp-nextjs
    - docker build -t hrerp/nextjs-app:latest -t hrerp/nextjs-app:$CI_COMMIT_SHA .
    - docker run -d -p 3000:3000 --name hrerp-nextjs hrerp/nextjs-app:$CI_COMMIT_SHA
